# Generated by Django 2.1.15 on 2020-09-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_reicpe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reicpe',
            new_name='Recipe',
        ),
    ]
